services:
  postgres-db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: noteapp
      POSTGRES_PASSWORD: noteapp1
      POSTGRES_DB: NoteApp
    ports:
      - "5433:5432"